### ISSUE TITLE
Allowing forks to build other branches

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#118]
Currently the `.travis.yml` looks like this:

```yml

branches:
  only:
    # Pushes and PR to the master branch.
    - master
```

This prevents other branches from building in CI. The way I get my other branches to build is by:

- 1. changing the travis.yml file for a branch
- 2. working on the branch in my repo
- 3. change the travis.yml file back
- 4. pull-request

Is there a way to improve this ? I basically rely on travis and the docker images for running tests on all platforms.
